FROM ubuntu:latest
RUN mkdir -p /WORK
WORKDIR /WORK
RUN apt update   
RUN apt-get install -y --no-install-recommends    \
     libglib2.0-0         libfontconfig1     \

# MXE Requirements
RUN apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    autopoint \
    bash \
    bison \
    bzip2 \
    flex \
    g++ \
    g++-multilib \
    gettext \
    git \
    gperf \
    intltool \
    libc6-dev-i386 \
    libgdk-pixbuf2.0-dev \
    libltdl-dev \
    libgl-dev \
    libssl-dev \
    libtool-bin \
    libxml-parser-perl \
    lzip \
    make \
    openssl \
    p7zip-full \
    patch \
    perl \
    python3 \
    python3-mako \
    python3-pkg-resources \
    ruby \
    sed \
    unzip \
    wget \
    xz-utils
RUN      rm -rf /var/lib/apt/lists/*     
WORKDIR /work
RUN    git clone --depth 1 https://github.com/mxe/mxe.git 
RUN   ln -s /usr/bin/python3 /usr/bin/python
RUN   make 
